services:
  backend:
    build: ./backend
    ports:
      - "8081:8081"
      - "5005:5005"
    env_file:
      - ./backend/.env.docker
    environment:
      APP_UPLOAD_LOCAL_BASE_PATH: /usr/share/nginx/html
    volumes:
      - ./backend/build/classes:/app/build/classes 
      - ./backend/build/resources:/app/build/resources 
      - ./backend/src/main/resources/kitnetapi-firebase-adminsdk-fbsvc-f31bd8bec4.json:/app/src/main/resources/kitnetapi-firebase-adminsdk-fbsvc-f31bd8bec4.json
      - ./backend/build/libs:/app/build/libs
    command: ["java", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "/app/app.jar", "--spring.profiles.active=dev"]
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
    restart: on-failure
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USERNAME: ${DATABASE_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=caching_sha2_password
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    env_file:
      - ./frontend/.env.docker
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: ["node_modules/.bin/next", "dev", "-p", "3000"]

  minio:
      image: minio/minio
      container_name: minio_server
      ports:
        - "9000:9000"
        - "9001:9001"
      volumes:
        - minio_data:/data
      environment:
        MINIO_ROOT_USER: rootuser
        MINIO_ROOT_PASSWORD: rootpassword
      command: server /data --console-address ":9001"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
        interval: 30s
        timeout: 20s
        retries: 3

  cdn_proxy:
      image: nginx:1.25.1
      container_name: kitnet-cdn-proxy
      ports:
        - "80:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - minio

volumes:
  db_data:
  minio_data: